//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Thrusters : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single RightDownThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_RightDownThruster;
            }
        }
        
        public virtual SteamVR_Action_Single LeftDownThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_LeftDownThruster;
            }
        }
        
        public virtual SteamVR_Action_Single RightDirectionalThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_RightDirectionalThruster;
            }
        }
        
        public virtual SteamVR_Action_Single LeftDirectionalThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_LeftDirectionalThruster;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reset
        {
            get
            {
                return SteamVR_Actions.thrusters_Reset;
            }
        }
        
        public virtual SteamVR_Action_Single LeftReversedDirectionalThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_LeftReversedDirectionalThruster;
            }
        }
        
        public virtual SteamVR_Action_Single RightReversedDirectionalThruster
        {
            get
            {
                return SteamVR_Actions.thrusters_RightReversedDirectionalThruster;
            }
        }
    }
}
